namespaceOverride:
  devops
controller:
  serviceType: LoadBalancer
  servicePort: 8080
  serviceAnnotations: {
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing",
    service.beta.kubernetes.io/aws-load-balancer-name: "annz-jenkins-lb",
    service.beta.kubernetes.io/load-balancer-source-ranges: "10.0.0.0/24,172.16.0.0/12",
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxx,subnet-yyyyyyy", # to be updated
    sservice.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true",
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:123456789012:certificate/your-cert-id", # to be updated
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp",
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
  }
  serviceLabels: {}
  podLabels: {"svc":"jenkins-master"}
  additionalPlugins:
    - blueocean:1.27.21
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
  ingress:
    enabled: true
persistence:
    enabled: true
    # storageClass: "annz-jenkins-sc" # use EBS
    existingClaim: "devops-efs-sc-pvc"
    accessMode: "ReadWriteMany"
agent:
  podName: default
  customJenkinsLabels: default
  serviceAccount: jenkins
  envVars:
  - name: HOME
    value: /home/jenkins/agent
  - name: PATH
    value: /usr/local/bin
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
  additionalAgents:
    python:
      podName: python
      customJenkinsLabels: python
      sideContainerName: python
      image:
        repository: python
        tag: "3"
      command: "/bin/sh -c"
      args: "cat"
      TTYEnabled: true
  disableDefaultAgent: true
  podTemplates:
    python: |
      - name: python
        label: jenkins-python
        serviceAccount: jenkins
        containers:
          - name: python
            image: python:3
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"
  volumes:
    - type: EmptyDir
      mountPath: /var/myapp/myemptydir
      memory: false